### ISSUE TITLE
分辨率125%不兼容

### ISSUE THREAD

**Issue by sunlight007** [lanshiqin/JerryMouse#2]
现在的笔记本大多数都是以125%的分辨率，使用后录放的位置不正确

**Comment by sunlight007** [comment]
我试了一下，把run函数里x、y、x_axis、y_axis后面都加上/1.25，可以兼容

**Comment by sunlight007** [comment]
我觉得可以在写一个填写电脑缩放比率，然后就对应数值，这样才能兼容更多电脑

**Comment by lanshiqin** [comment]
> 我觉得可以在写一个填写电脑缩放比率，然后就对应数值，这样才能兼容更多电脑

可以考虑加一个自动获取分辨率的代码

**Comment by lanshiqin** [comment]
感谢指出，已兼容分辨率问题
